name: Test KICS action PR comment

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run kics Scan
      uses: checkmarx/kics-github-action@v1.6
        with:
          path: test/samples/positive1.tf,test/samples/positive2.tf
          token: ${{ secrets.GITHUB_TOKEN }}
          output_path: myResults/
          ignore_on_exit: results
          enable_comments: true
