name: Reviewdog
on: [pull_request]
jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: reviewdog
      uses: reviewdog/action-detect-secrets@2c14c1ff638516f39eeb97a927f95d28d9dbb62d #v0.11.4
      with:
        reporter: github-pr-review
        fail-on-error: true
