name: Reviewdog
on: [pull_request]
jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: reviewdog
      uses: reviewdog/action-detect-secrets@master
      with:
        reporter: github-pr-review 
